# -*- coding: utf-8 -*-
"""chapter16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AQU-lOK14SrV_D49Dhbvh2nufBs3aBKY
"""

from google.colab import drive
import os
import csv

drive.mount('./gdrive', force_remount = True)
print(os.getcwd())
f= open('./gdrive/MyDrive/Colab Notebooks/temperature.csv', 'r', encoding='cp949')
data = csv.reader(f, delimiter=',')
header = next(data)
max_temp=-999
max_temp_date=""
for row in data:
  if row[-1] != '':
    row[-1] = float(row[-1])
    if max_temp < row[-1]:
      max_temp = row[-1]
      max_temp_date = row[0]

print("기상 관측 이래, 최고 기온이 가장 높았던 날은 {0}로, {1} 도 입니다.".format(max_temp_date, max_temp))
f.close()